### ISSUE TITLE
Категории в Агентских (клиентских) заказах в кабинетах.

### ISSUE THREAD

**Issue by tgedanke** [DaViSx13/flip-web#25]
![image](https://user-images.githubusercontent.com/4849369/141501752-0b0fa040-a49a-4840-bc0d-a2545930bc83.png)

1. Убрать опасный груз.
2. Добавить чекбоксы Категория груза. В видет чекбоксов или комбо чек бокса.
![image](https://user-images.githubusercontent.com/4849369/141502005-9301ee00-1ebb-4c6b-8c2b-ee8d10f52357.png)
В базе это хранится в виде битовой маски. в поле SortType
таблица AgOrders 

![image](https://user-images.githubusercontent.com/4849369/141686480-c4cc0df5-f9de-48a2-865a-cb589fc6023f.png)

**Comment by vb010894** [comment]
Отправил на тест
