### ISSUE TITLE
Расчеты  с агентами - оплата

### ISSUE THREAD

**Issue by DaViSx13** [DaViSx13/flip-web#5]
Добавить отображение поля "Оплата" из расчетов с агентами.
![image](https://user-images.githubusercontent.com/11454751/31715634-556cc096-b40d-11e7-8c04-97694c31a8c2.png)
![image](https://user-images.githubusercontent.com/11454751/31715734-a036baa0-b40d-11e7-8e05-9406b9967e2f.png)

**Comment by tgedanke** [comment]
Код положил на сервер, но пока хорошо не тестировал и не проверял сборку с мультиязычностью

**Comment by tgedanke** [comment]
![mqf_kip](https://user-images.githubusercontent.com/4849369/31985055-6391ba64-b96c-11e7-996e-49fdbd02c2bb.png)
Вот
